## 基本は github.com のレポジトリーを指定するだけ
#[[plugins]]
#repo = 'Shougo/dein.vim'
#
## git clone 後、実行すべきコマンドがある場合はこんな感じ
#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#
#  [plugins.build]
#  windows = 'tools\\update-dll-mingw'
#  cygwin  = 'make -f make_cygwin.mak'
#  mac     = 'make -f make_mac.mak'
#  linux   = 'make'
#  unix    = 'gmake'
#
## ブランチやタグを指定したいとき
#[[plugins]]
#repo = 'delphinus35/typescript-vim'
#rev  = 'colorize-template-strings'
#
## 特定の条件で読み込みたいとき
#[[plugins]]
#repo = 'elzr-vim-json'
#if   = '''! has('kaoriya')'''
#
## 依存関係を指定したいとき
#[[plugins]]
#repo    = 'vim-airline/vim-airline'
#depends = ['vim-airline-themes']
#
## 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'

# 補完系
[[plugins]]
repo = 'Shougo/neocomplcache'
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Markdown
# 編集しているファイルを自動保存するために必要
# 'vim-scripts/vim-auto-save'
# Vim で編集した Markdownファイルをブラウザプレビューするために必要(自動リロード機能付き)
[[plugins]]
repo = 'kannokanno/previm'
# 連続スクロールを実現するために必要
[[plugins]]
repo = 'kana/vim-submode'
# ブラウザでプレビューするために必要
[[plugins]]
repo = 'tyru/open-browser.vim'

# ruby & rails
# gfで移動, 元に戻るにはC-o, :A, :R
[[plugins]]
repo = 'rails.vim'
# Ruby向けにendを自動挿入してくれる
[[plugins]]
repo = 'tpope/vim-endwise'
#「%」コマンドの強化, 対応するタグ移動
[[plugins]]
repo = 'matchit.zip'
# コーディングルールチェック
# NeoBundle 'scrooloose/syntastic'
# let g:syntastic_mode_map = { 'mode': 'passive',
#             \ 'active_filetypes': ['ruby'] }
# let g:syntastic_ruby_checkers = ['rubocop']
# Rails版unite
# NeoBundle 'https://github.com/basyura/unite-rails.git'


[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'Shougo/vimshell'

# ファイルオープンを便利にする
[[plugins]]
repo = 'Shougo/unite.vim'
# シングルクオートとダブルクオートの入れ替え等
[[plugins]]
repo = 'tpope/vim-surround'
# ファイルをツリー表示してくれる
[[plugins]]
repo = 'scrooloose/nerdtree'
# \cでコメントアウトできる
[[plugins]]
repo = 'tyru/caw.vim.git'
nmap <Leader>c <Plug>(caw:i:toggle)
vmap <Leader>c <Plug>(caw:i:toggle)
# 行末に半角スペースがあると色付けしてくれる
[[plugins]]
repo = 'https://github.com/bronson/vim-trailing-whitespace'

# ログファイルを色づけしてくれる
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

# editorconfigをvimで適応させるやつ
[[plugins]]
repo = 'https://github.com/editorconfig/editorconfig-vim'

# ノーマルモードになったら自動で保存
[[plugins]]
repo = 'syui/airsave.vim'

# ag
[[plugins]]
repo = 'rking/ag.vim'

# erbインデントON
[[plugins]]
repo = 'othree/html5.vim'

# color
[[plugins]]
repo = 'tyru/caw.vim.git'
NeoBundle 'tomasr/molokai'

# slim syntax
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'slim-template/vim-slim.git'
syntax enable
filetype plugin indent on

# :Switchでキーワード切り替え
NeoBundle #AndrewRadev/switch.vim"
[[plugins]]
repo = 'tyru/caw.vim.git'
