# 補完系
[[plugins]]
repo = 'Shougo/vimproc'
# TODO: snippet効かない問題
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neocomplete.vim'

# Markdown
# 編集しているファイルを自動保存するために必要
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
# Vim で編集した Markdownファイルをブラウザプレビューするために必要repo = 自動リロード機能付き
[[plugins]]
repo = 'kannokanno/previm'
# 連続スクロールを実現するために必要
[[plugins]]
repo = 'kana/vim-submode'
# ブラウザでプレビューするために必要
[[plugins]]
repo = 'tyru/open-browser.vim'

# ruby & rails
# gfで移動, 元に戻るにはC-o, :A, :R
[[plugins]]
repo = 'tpope/vim-rails'
# Ruby向けにendを自動挿入してくれる
[[plugins]]
repo = 'tpope/vim-endwise'
#「%」コマンドの強化, 対応するタグ移動
[[plugins]]
repo = 'matchit.zip'
# コーディングルールチェック
[[plugins]]
repo = 'scrooloose/syntastic'
# Rails版unite
[[plugins]]
repo = 'basyura/unite-rails.git'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'Shougo/vimshell'

# ファイルオープンを便利にする
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

# シングルクオートとダブルクオートの入れ替え等
# 'を"に変更 => cs'"
# 行全体を囲む => yss'
# 選択した範囲を囲む => 選択後S'
# 削除       => ds
# 単語を囲む => ysiw
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'surround.vim'

# ファイルをツリー表示してくれる
[[plugins]]
repo = 'scrooloose/nerdtree'

# \cでコメントアウトできる
[[plugins]]
repo = 'https://github.com/tyru/caw.vim'

# 行末に半角スペースがあると色付けしてくれる
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ログファイルを色づけしてくれる
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

# editorconfigをvimで適応させるやつ
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# ノーマルモードになったら自動で保存
[[plugins]]
repo = 'syui/airsave.vim'

# ag
[[plugins]]
repo = 'rking/ag.vim'
[plugins.build]
mac     = 'make -f make_mac.mak'

# erbインデントON
# カラースキーマ設定
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'jelera/vim-javascript-syntax'

# htmlの文法チェック
[[plugins]]
repo = 'hokaccha/vim-html5validator'

# HTMLファイルを修正して保存したタイミングで, そのHTMLを表示しているブラウザが自動で再読み込みする
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

# color
[[plugins]]
repo = 'tomasr/molokai'

# slim syntax
[[plugins]]
repo = 'slim-template/vim-slim.git'

# :Switchでキーワード切り替え
[[plugins]]
repo = 'AndrewRadev/switch.vim'

# ステータスライン強化
[[plugins]]
repo = 'itchyny/lightline.vim'

# html補完
# http://qiita.com/muran001/items/9ce24525b3285678acc3
# Emmet式<C-y>, で展開できる
[[plugins]]
repo = 'mattn/emmet-vim'

# vimのスタート画面をいい感じにしてくれる
# なんか日本語表記になってないっぽい
[[plugins]]
repo = 'mhinz/vim-startify'

# コンテキストに応じて, ファイルタイプを変更できる
[[plugins]]
repo = 'osyo-manga/vim-precious'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
