[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# 補完系辞書
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# 補完
# luaをインスコしているのが前提
# http://cpp0302.hatenablog.com/entry/2015/04/10/033609
# http://qiita.com/hide/items/229ff9460e75426a2d07
# <TAB> 補完候補の選択
# C-g   補完した文字を消す
# C-l   補完候補の中から, 共通する部分を補完
[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

# Markdown
# 編集しているファイルを自動保存するために必要
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
# Vimで編集したMarkdownファイルをブラウザプレビューするために必要
[[plugins]]
repo = 'kannokanno/previm'
# ブラウザでプレビューするために必要
[[plugins]]
repo = 'tyru/open-browser.vim'

# Ruby&Rails
# gfで移動, 元に戻るにはC-o, :A, :R
[[plugins]]
repo = 'tpope/vim-rails'
# Ruby向けにendを自動挿入してくれる
[[plugins]]
repo = 'tpope/vim-endwise'
#「%」コマンドの強化, 対応するタグ移動
[[plugins]]
repo = 'matchit.zip'
# Rails版unite
[[plugins]]
repo = 'basyura/unite-rails.git'

[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# ファイルオープンを便利にする
[[plugins]]
repo = 'Shougo/neomru.vim'

# 検索
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

# シングルクオートとダブルクオートの入れ替え等
# 'を"に変更        : cs'"
# 行全体を囲む      : yss'
# 選択した範囲を囲む: 選択後S'
# 削除              : ds
# 単語を囲む        : ysiw
[[plugins]]
repo = 'tpope/vim-surround'

# ファイルをツリー表示してくれる
[[plugins]]
repo = 'scrooloose/nerdtree'
# nerdtreeをすべてのタブで共通化する
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

# \cでコメントアウトできる
[[plugins]]
repo = 'https://github.com/tyru/caw.vim'

# 行末に半角スペースがあると色付けしてくれる
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ログファイルを色づけしてくれる
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

# editorconfigをvimで適応させるやつ
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# ノーマルモードになったら自動で保存
[[plugins]]
repo = 'syui/airsave.vim'

# ag
[[plugins]]
repo = 'rking/ag.vim'

# erbインデントON
# カラースキーマ設定
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
[[plugins]]
repo = 'jelera/vim-javascript-syntax'

# HTMLファイルを修正して保存したタイミングで, そのHTMLを表示しているブラウザが自動で再読み込みする
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

# color
[[plugins]]
repo = 'tomasr/molokai'

# ステータスライン強化
[[plugins]]
repo = 'itchyny/lightline.vim'

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# jsonファイルのダブルクォーテーションを表示する
[[plugins]]
repo = 'elzr/vim-json'

# html補完
# http://qiita.com/muran001/items/9ce24525b3285678acc3
# Emmet式<C-y>, で展開できる
[[plugins]]
repo = 'mattn/emmet-vim'
# ------------------------------------------------------
# vimのスタート画面をいい感じにしてくれる
# なんか日本語表記になってないっぽい
# [[plugins]]
# repo = 'mhinz/vim-startify'

# コンテキストに応じて, ファイルタイプを変更できる
# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# [[plugins]]
# repo = 'Shougo/context_filetype.vim'
# htmlの文法チェック
# [[plugins]]
# repo = 'hokaccha/vim-html5validator'
# :Switchでキーワード切り替え
# [[plugins]]
# repo = 'AndrewRadev/switch.vim'

# # 連続スクロールを実現するために必要
# [[plugins]]
# repo = 'kana/vim-submode'

# slim syntax
# [[plugins]]
# repo = 'slim-template/vim-slim.git'

# コーディングルールチェック
# # [[plugins]]
# # repo = 'scrooloose/syntastic'
